#include "config/config.h"

#include "util/log.h"
#include "util/path.h"

#include <lauxlib.h>
#include <lua.h>
#include <lualib.h>
#include <stdio.h>
#include <string.h>

int traash_config_init(TraashConfig *cfg) {
  memset(cfg, 0, sizeof(*cfg));
  snprintf(cfg->theme, sizeof(cfg->theme), "tokyo-night");
  snprintf(cfg->status_bar, sizeof(cfg->status_bar), "pills");
  snprintf(cfg->font_family, sizeof(cfg->font_family), "monospace");
  cfg->font_size = 14.0f;
  cfg->opacity = 1.0f;
  cfg->cursor_style = 1;
  cfg->scrollback_lines = 5000;
  cfg->default_layout[0] = 0;
  cfg->lua = luaL_newstate();
  if (!cfg->lua) {
    return -1;
  }
  luaL_openlibs((lua_State *)cfg->lua);
  return 0;
}

void traash_config_shutdown(TraashConfig *cfg) {
  if (cfg->lua) {
    lua_close((lua_State *)cfg->lua);
    cfg->lua = NULL;
  }
}

static void read_string_field(lua_State *L, const char *key, char *dst, size_t n,
                              const char *defv) {
  lua_getfield(L, -1, key);
  if (lua_isstring(L, -1) && lua_tostring(L, -1)[0]) {
    snprintf(dst, n, "%s", lua_tostring(L, -1));
  } else {
    snprintf(dst, n, "%s", defv);
  }
  lua_pop(L, 1);
}

static void read_number_field(lua_State *L, const char *key, float *dst, float defv) {
  lua_getfield(L, -1, key);
  if (lua_isnumber(L, -1)) {
    *dst = (float)lua_tonumber(L, -1);
  } else {
    *dst = defv;
  }
  lua_pop(L, 1);
}

int traash_config_load(TraashConfig *cfg) {
  lua_State *L = (lua_State *)cfg->lua;
  char lua_dir[512];
  char path[640];
  traash_lua_dir(lua_dir, sizeof(lua_dir));

  /* package.path */
  lua_getglobal(L, "package");
  lua_getfield(L, -1, "path");
  const char *old = lua_tostring(L, -1);
  char newpath[2048];
  snprintf(newpath, sizeof(newpath), "%s/?.lua;%s/?/init.lua;%s", lua_dir, lua_dir,
           old ? old : "");
  lua_pop(L, 1);
  lua_pushstring(L, newpath);
  lua_setfield(L, -2, "path");
  lua_pop(L, 1);

  snprintf(path, sizeof(path), "%s/defaults/config.lua", lua_dir);
  if (luaL_dofile(L, path) != LUA_OK) {
    TRAASH_LOGW("defaults config: %s", lua_tostring(L, -1));
    lua_pop(L, 1);
  } else {
    lua_pop(L, 1); /* returned config table */
  }

  char confdir[512];
  char user_cfg[640];
  if (traash_config_dir(confdir, sizeof(confdir)) == 0) {
    snprintf(user_cfg, sizeof(user_cfg), "%s/config.lua", confdir);
    if (luaL_dofile(L, user_cfg) == LUA_OK) {
      TRAASH_LOGI("loaded %s", user_cfg);
      lua_pop(L, 1); /* returned config table */
    } else {
      lua_pop(L, 1);
    }
  }

  lua_getglobal(L, "config");
  if (!lua_istable(L, -1)) {
    lua_pop(L, 1);
    cfg->loaded = true;
    return 0;
  }
  read_string_field(L, "theme", cfg->theme, sizeof(cfg->theme), "tokyo-night");
  read_string_field(L, "status_bar", cfg->status_bar, sizeof(cfg->status_bar),
                    "pills");
  read_string_field(L, "font", cfg->font_family, sizeof(cfg->font_family),
                    "monospace");
  read_number_field(L, "font_size", &cfg->font_size, 14.0f);
  read_number_field(L, "opacity", &cfg->opacity, 1.0f);
  lua_getfield(L, -1, "cursor_style");
  if (lua_isnumber(L, -1)) {
    cfg->cursor_style = (int)lua_tointeger(L, -1);
  }
  lua_pop(L, 1);
  lua_getfield(L, -1, "scrollback");
  if (lua_isnumber(L, -1)) {
    cfg->scrollback_lines = (int)lua_tointeger(L, -1);
  }
  lua_pop(L, 1);
  read_string_field(L, "default_layout", cfg->default_layout, sizeof(cfg->default_layout),
                    "");

  cfg->plugin_count = 0;
  lua_getfield(L, -1, "plugins");
  if (lua_istable(L, -1)) {
    lua_pushnil(L);
    while (lua_next(L, -2) != 0 && cfg->plugin_count < 16) {
      if (lua_isstring(L, -1)) {
        snprintf(cfg->plugins[cfg->plugin_count], sizeof(cfg->plugins[0]), "%s",
                 lua_tostring(L, -1));
        cfg->plugin_count++;
      }
      lua_pop(L, 1);
    }
  }
  lua_pop(L, 1); /* plugins */
  lua_pop(L, 1); /* config */
  cfg->loaded = true;
  return 0;
}

int traash_config_reload(TraashConfig *cfg) {
  return traash_config_load(cfg);
}

int traash_config_save(const TraashConfig *cfg, const TraashKeymap *km) {
  char confdir[512];
  char path[640];
  if (traash_config_dir(confdir, sizeof(confdir)) != 0) {
    return -1;
  }
  snprintf(path, sizeof(path), "%s/config.lua", confdir);
  FILE *f = fopen(path, "w");
  if (!f) {
    return -1;
  }
  fprintf(f, "-- Generated by traa.sh settings\n");
  fprintf(f, "config = {\n");
  fprintf(f, "  theme = \"%s\",\n", cfg->theme);
  fprintf(f, "  status_bar = \"%s\",\n", cfg->status_bar);
  fprintf(f, "  font = \"%s\",\n", cfg->font_family);
  fprintf(f, "  font_size = %.0f,\n", cfg->font_size);
  fprintf(f, "  opacity = %.2f,\n", cfg->opacity);
  fprintf(f, "  cursor_style = %d,\n", cfg->cursor_style);
  fprintf(f, "  scrollback = %d,\n", cfg->scrollback_lines);
  fprintf(f, "  default_layout = \"%s\",\n", cfg->default_layout);
  fprintf(f, "  plugins = {\n");
  for (int i = 0; i < cfg->plugin_count; i++) {
    fprintf(f, "    \"%s\",\n", cfg->plugins[i]);
  }
  fprintf(f, "  },\n");
  if (km) {
    fprintf(f, "  leader = { key = %d, mods = %d },\n", km->prefix_key, km->prefix_mods);
  }
  fprintf(f, "  keys = {\n");
  if (km) {
    for (int i = 0; i < km->count; i++) {
      const TraashKeyBind *b = &km->binds[i];
      fprintf(f, "    { action = \"%s\", key = %d, mods = %d, prefix = %d },\n",
              traash_action_name(b->action), b->key, b->mods, b->prefix);
    }
  }
  fprintf(f, "  },\n");
  fprintf(f, "}\n");
  fprintf(f, "return config\n");
  fclose(f);
  TRAASH_LOGI("wrote %s", path);
  return 0;
}

int traash_config_apply_keys(TraashConfig *cfg, TraashKeymap *km) {
  if (!cfg->lua || !km) {
    return -1;
  }
  lua_State *L = (lua_State *)cfg->lua;
  lua_getglobal(L, "config");
  if (!lua_istable(L, -1)) {
    lua_pop(L, 1);
    return 0;
  }

  lua_getfield(L, -1, "leader");
  if (lua_istable(L, -1)) {
    lua_getfield(L, -1, "key");
    int key = lua_isnumber(L, -1) ? (int)lua_tointeger(L, -1) : 0;
    lua_pop(L, 1);
    lua_getfield(L, -1, "mods");
    int mods = lua_isnumber(L, -1) ? (int)lua_tointeger(L, -1) : 0;
    lua_pop(L, 1);
    if (key) {
      traash_keymap_normalize_key(&key, &mods);
      traash_keymap_set_leader(km, key, mods);
    }
  }
  lua_pop(L, 1); /* leader */

  lua_getfield(L, -1, "keys");
  if (!lua_istable(L, -1)) {
    lua_pop(L, 2);
    return 0;
  }
  /* Overlay saved binds onto defaults so newly added actions (e.g. shortcuts)
   * keep working when an older config.lua is loaded. */
  lua_pushnil(L);
  while (lua_next(L, -2) != 0) {
    if (lua_istable(L, -1)) {
      lua_getfield(L, -1, "action");
      const char *an = lua_isstring(L, -1) ? lua_tostring(L, -1) : "";
      TraashAction act = traash_action_from_name(an);
      lua_pop(L, 1);
      lua_getfield(L, -1, "key");
      int key = lua_isnumber(L, -1) ? (int)lua_tointeger(L, -1) : 0;
      lua_pop(L, 1);
      lua_getfield(L, -1, "mods");
      int mods = lua_isnumber(L, -1) ? (int)lua_tointeger(L, -1) : 0;
      lua_pop(L, 1);
      lua_getfield(L, -1, "prefix");
      int prefix = lua_isnumber(L, -1) ? (int)lua_tointeger(L, -1) : 0;
      lua_pop(L, 1);
      if (act != TRAASH_ACTION_NONE && key) {
        traash_keymap_rebind(km, act, key, mods, prefix);
      }
    }
    lua_pop(L, 1);
  }
  lua_pop(L, 2);

  /* Older saved keymaps may omit newer actions; keep shipping defaults. */
  if (!traash_keymap_find_action(km, TRAASH_ACTION_LAYOUT_PICKER, NULL)) {
    traash_keymap_bind(km, 76 /* L */, 1 | 2, 0, TRAASH_ACTION_LAYOUT_PICKER);
  }
  if (!traash_keymap_find_action(km, TRAASH_ACTION_GOTO_WINDOW, NULL)) {
    traash_keymap_bind(km, '1', 0, 1, TRAASH_ACTION_GOTO_WINDOW);
  }
  if (!traash_keymap_find_action(km, TRAASH_ACTION_OVERVIEW, NULL)) {
    traash_keymap_bind(km, 79 /* O */, 1 | 2, 0, TRAASH_ACTION_OVERVIEW);
  }
  return 0;
}

