#ifndef TRAASH_ACTIONS_H
#define TRAASH_ACTIONS_H

typedef enum {
  TRAASH_ACTION_NONE = 0,
  TRAASH_ACTION_SPLIT_H,
  TRAASH_ACTION_SPLIT_V,
  TRAASH_ACTION_PANE_NEXT,
  TRAASH_ACTION_PANE_LEFT,
  TRAASH_ACTION_PANE_DOWN,
  TRAASH_ACTION_PANE_UP,
  TRAASH_ACTION_PANE_RIGHT,
  TRAASH_ACTION_ZOOM,
  TRAASH_ACTION_NEW_WINDOW,
  TRAASH_ACTION_NEXT_WINDOW,
  TRAASH_ACTION_PREV_WINDOW,
  TRAASH_ACTION_GOTO_WINDOW, /* prefix+0..9; target in keymap.goto_window */
  TRAASH_ACTION_DETACH,
  TRAASH_ACTION_RELOAD_CONFIG,
  TRAASH_ACTION_COMMAND_PALETTE,
  TRAASH_ACTION_THEME_CYCLE,
  TRAASH_ACTION_STATUS_CYCLE,
  TRAASH_ACTION_FONT_INCREASE,
  TRAASH_ACTION_FONT_DECREASE,
  TRAASH_ACTION_DEMO,
  TRAASH_ACTION_COPY_MODE,
  TRAASH_ACTION_COPY,
  TRAASH_ACTION_PASTE,
  TRAASH_ACTION_SEARCH,
  TRAASH_ACTION_SETTINGS,
  TRAASH_ACTION_SHORTCUTS,
  TRAASH_ACTION_LAYOUT_PICKER,
  TRAASH_ACTION_OVERVIEW,
  TRAASH_ACTION_QUIT,
  TRAASH_ACTION_COUNT
} TraashAction;

const char *traash_action_name(TraashAction a);
const char *traash_action_label(TraashAction a);
TraashAction traash_action_from_name(const char *name);

#endif
