#ifndef TRAASH_SHORTCUT_CATALOG_H
#define TRAASH_SHORTCUT_CATALOG_H

#include "input/actions.h"

typedef struct {
  const char *title;
  const TraashAction *actions;
  int count;
} TraashShortcutGroup;

static const TraashAction TRAASH_SHORTCUT_PANES[] = {
    TRAASH_ACTION_SPLIT_H,    TRAASH_ACTION_SPLIT_V,   TRAASH_ACTION_PANE_NEXT,
    TRAASH_ACTION_PANE_LEFT,  TRAASH_ACTION_PANE_DOWN, TRAASH_ACTION_PANE_UP,
    TRAASH_ACTION_PANE_RIGHT, TRAASH_ACTION_ZOOM};

static const TraashAction TRAASH_SHORTCUT_WINDOWS[] = {
    TRAASH_ACTION_NEW_WINDOW, TRAASH_ACTION_NEXT_WINDOW, TRAASH_ACTION_PREV_WINDOW,
    TRAASH_ACTION_GOTO_WINDOW, TRAASH_ACTION_DETACH, TRAASH_ACTION_LAYOUT_PICKER,
    TRAASH_ACTION_OVERVIEW};

static const TraashAction TRAASH_SHORTCUT_EDIT[] = {
    TRAASH_ACTION_COPY, TRAASH_ACTION_PASTE, TRAASH_ACTION_SEARCH, TRAASH_ACTION_COPY_MODE};

static const TraashAction TRAASH_SHORTCUT_APPEARANCE[] = {
    TRAASH_ACTION_THEME_CYCLE, TRAASH_ACTION_STATUS_CYCLE, TRAASH_ACTION_FONT_INCREASE,
    TRAASH_ACTION_FONT_DECREASE, TRAASH_ACTION_SETTINGS};

static const TraashAction TRAASH_SHORTCUT_APP[] = {
    TRAASH_ACTION_COMMAND_PALETTE, TRAASH_ACTION_SHORTCUTS, TRAASH_ACTION_LAYOUT_PICKER,
    TRAASH_ACTION_OVERVIEW, TRAASH_ACTION_RELOAD_CONFIG, TRAASH_ACTION_DEMO, TRAASH_ACTION_QUIT};

static const TraashShortcutGroup TRAASH_SHORTCUT_GROUPS[] = {
    {"Panes", TRAASH_SHORTCUT_PANES,
     (int)(sizeof(TRAASH_SHORTCUT_PANES) / sizeof(TRAASH_SHORTCUT_PANES[0]))},
    {"Windows", TRAASH_SHORTCUT_WINDOWS,
     (int)(sizeof(TRAASH_SHORTCUT_WINDOWS) / sizeof(TRAASH_SHORTCUT_WINDOWS[0]))},
    {"Edit", TRAASH_SHORTCUT_EDIT,
     (int)(sizeof(TRAASH_SHORTCUT_EDIT) / sizeof(TRAASH_SHORTCUT_EDIT[0]))},
    {"Appearance", TRAASH_SHORTCUT_APPEARANCE,
     (int)(sizeof(TRAASH_SHORTCUT_APPEARANCE) / sizeof(TRAASH_SHORTCUT_APPEARANCE[0]))},
    {"Application", TRAASH_SHORTCUT_APP,
     (int)(sizeof(TRAASH_SHORTCUT_APP) / sizeof(TRAASH_SHORTCUT_APP[0]))},
};

static inline int traash_shortcut_group_count(void) {
  return (int)(sizeof(TRAASH_SHORTCUT_GROUPS) / sizeof(TRAASH_SHORTCUT_GROUPS[0]));
}

#endif
